Repository refolded/tokei-backend, pull requests merged in 2021-08, with the labels that each got.

#1 feat: add commitlint and initialize project
  .husky/commit-msg
  commitlint.config.js
  package.json
  pull_request_template.md
  yarn.lock
Labels: documentation, enhancement, good first issue

#2 feat: add express, typescript, apollo and eslint
  .env.example
  .eslintignore
  .eslintrc
  .gitignore
  index.ts
  package.json
  tsconfig.json
  yarn.lock
Labels: enhancement

#3 feat: add prisma and extract typedefs and resolvers
  .env.example
  .eslintrc
  graphql/resolvers/index.ts
  graphql/typedefs/index.ts
  index.ts
  package.json
  prisma/schema.prisma
  yarn.lock
Labels: cleanup, enhancement

#4 feat: add schema v1
  prisma/schema.prisma
Labels: enhancement

#6 docs: add read me
  README.md
Labels: cleanup, documentation, good first issue

#7 refactor: make graphQL schema code modular
  graphql/resolvers/index.ts
  graphql/schema.ts
  graphql/typedefs/index.ts
  index.ts
  package.json
  yarn.lock
Labels: enhancement, good first issue

#8 feat: initialize prisma in apollo and add standard-version
  .versionrc.json
  README.md
  index.ts
  package.json
  prisma/context.ts
  yarn.lock
Labels: enhancement, good first issue

#9 fix: :fire: add entity for project administrators
  prisma/schema.prisma
Labels: bug, enhancement

#11 refactor: :zap: switch property collection to an array
  prisma/schema.prisma
Labels: bug, enhancement

#12 feat: add sentry
  graphql/plugins/sentry.ts
  index.ts
  package.json
  yarn.lock
Labels: enhancement, good first issue

#13 feat: add missing properties
  prisma/schema.prisma
Labels: cleanup, enhancement

#18 feat: add graphql schema property
  graphql/resolvers/property.ts
  graphql/schema.ts
  graphql/typedefs/property.ts
  package.json
  yarn.lock
Labels: enhancement
